version: '3.8'

services:
  # Node.js API server
  api-server:
    container_name: AVF-Pro-API
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped

  # Your Nginx web server (now acts as reverse proxy)
  webserver:
    container_name: AVF-Pro-Webserver 
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Updated nginx config
    ports:
      - "8080:80" # Map host port 8080 to container port 80 (for local testing)
    depends_on:
      - api-server
    networks:
      - app-network

  # Cloudflare Tunnel client
  cloudflared:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped # Automatically restart if it crashes
    command: tunnel --no-autoupdate run
    environment:
      # IMPORTANT: Replace this with your actual Tunnel Token from Cloudflare Zero Trust
      - TUNNEL_TOKEN=eyJhIjoiZWE5M2ZkNmNhNGFiYzBhOTI4OWExZmVjYzlkOTRkODciLCJ0IjoiNGJhNjQ5NzMtNjdjYy00ZjY1LWIxNGEtNzhlNjNkZGRlNWM2IiwicyI6Ik4yUXhNbU5oTmpZdE1UWXdOaTAwWlRsaExUa3hNbUV0T1dGbU1EY3lOekpqTURkaiJ9
    networks:
      - app-network # Crucial: Put both on the same network

networks:
  app-network:
    # This creates a custom bridge network so services can communicate by name
